checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php: '5.5.38'
    tests:
        override:
            -
                command: 'phpunit'
                coverage:
                    file: 'build/clover.xml'
                    format: 'clover'
